### ISSUE TITLE
How to correctly render multiple files? 

### ISSUE THREAD

**Issue by MateusRosario** [jitinnair1/autoCV#4]
I am using the template to build and deploy my CV, and it's very nice.

But I have modified the build.yml file to render two .tex files:  the cv (Portuguese version) and cv-en (English version).

Here you can see the modifications: https://github.com/MateusRosario/myAutoCV/blame/main/.github/workflows/build.yml

I just duplicated some steps with the new .tex file, and after some mistakes, it worked. But, being new at working with workflows, I would like to know if the way I did is the most efficent\expected way.

The comment "Edit here with the names of your latex file and directory" on line 9 got me thinking about it. So, could you @jitinnair1 enlighten me? And I hope this contributes to the template in some way.

**Comment by jitinnair1** [comment]
Thanks @MateusRosario for modifying the script to support multiple languages. 

It could be possible to simplify the script to avoid using `FILE` variables (like instead of using `FILE` and `FILE-EN` maybe use `FILE: cv.tex cv-en.tex`) but implementing it may be difficult and practically a user may need only two versions of their CV (one in their native language and one in English) so this script is great as it is.

I have linked your version of the script in the README for reference. Glad you found the repo and the script useful.
